// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCddeSldMw-C3Oeq3g4Qxzxw0Exldz_Srg',
    appId: '1:14186855767:web:83ea3109c257b5c6af9212',
    messagingSenderId: '14186855767',
    projectId: 'boutique-800c9',
    authDomain: 'boutique-800c9.firebaseapp.com',
    storageBucket: 'boutique-800c9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIakhh1wgqgDtUrAAx3nGIeBAqgMSTkiY',
    appId: '1:14186855767:android:2ad21dd9f8ca0869af9212',
    messagingSenderId: '14186855767',
    projectId: 'boutique-800c9',
    storageBucket: 'boutique-800c9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRPxZX0hM8fcKbhqFQWbdUhtLCXEXhClM',
    appId: '1:14186855767:ios:6e07b0bc90fff3e7af9212',
    messagingSenderId: '14186855767',
    projectId: 'boutique-800c9',
    storageBucket: 'boutique-800c9.appspot.com',
    iosBundleId: 'com.example.adminDashboard',
  );
}
